import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ChakraProviderOverride } from '@/utils/chakraProvider'
import { QueryProvider } from '@/utils/queryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Constel Social Network',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <ChakraProviderOverride>{children}</ChakraProviderOverride>
        </QueryProvider>
      </body>
    </html>
  )
}
